import Head from "next/head";
import { useRouter } from "next/router";
import { useEffect, useState } from "react";
import CratesNavbar from "../../components/CratesNavbar";
import ItemCard from "../../components/ItemCard";
import SpinnerLoader from "../../components/SpinnerLoader";
import { getCrates } from "../../services/csgo";

function capitalize(string) {
  if (!string) return "";
  return string.charAt(0).toUpperCase() + string.toLowerCase().slice(1);
}

export default function Post() {
  const router = useRouter();
  const { type } = router.query;

  const [loading, setLoading] = useState(false);
  const [crates, setCrates] = useState([]);

  useEffect(() => {
    async function getData() {
      try {
        setLoading(true);

        const { data } = await getCrates(type);

        setLoading(false);
        setCrates(data);
      } catch (e) {
        setCrates([]);
        console.error(e);
      }
    }
    getData();
  }, [type]);

  return (
    <>
      <Head>
        <title>
          Crates / {capitalize(type?.split("_").join(" "))} - CSGO DATA
        </title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <CratesNavbar />
      <SpinnerLoader loading={loading} />
      <div className="grid w-full gap-1 py-10 mx-auto items-grid-small md:items-grid">
        {crates.map((item) => {
          return (
            <ItemCard
              key={item.id}
              name={item.name}
              image={item.image}
            ></ItemCard>
          );
        })}
      </div>
    </>
  );
}
