import Head from "next/head";
import { useEffect, useState } from "react";
import CratesNavbar from "../../components/CratesNavbar";
import ItemCard from "../../components/ItemCard";
import SpinnerLoader from "../../components/SpinnerLoader";
import { getCrates } from "../../services/csgo";

export default function Crates() {
  const [loading, setLoading] = useState(false);
  const [crates, setCrates] = useState([]);
  const [showedItems, setShowedItems] = useState([]);

  useEffect(() => {
    async function getData() {
      try {
        setLoading(true);

        const { data } = await getCrates();

        setShowedItems(data.splice(0, 20));
        setCrates(data);
        setLoading(false);
      } catch (e) {
        setCrates([]);
        console.error(e);
      }
    }
    getData();
  }, []);

  useEffect(() => {
    window.addEventListener("scroll", handleScroll);
    return () => {
      window.removeEventListener("scroll", handleScroll);
    };
  });

  const handleScroll = () => {
    const lastItemLoaded = document.querySelector(
      ".items-grid > .group:last-child"
    );
    if (lastItemLoaded) {
      const lastItemLoadedOffset =
        lastItemLoaded.offsetTop + lastItemLoaded.clientHeight;
      const pageOffset = window.pageYOffset + window.innerHeight;

      if (pageOffset > lastItemLoadedOffset) {
        if (crates.length) {
          const all = crates;
          const selected = all.splice(0, 20);
          setShowedItems([...showedItems, ...selected]);
          setCrates(all);
        }
      }
    }
  };

  return (
    <>
      <Head>
        <title>Crates / All - CSGO ITEMS</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <CratesNavbar />
      <SpinnerLoader loading={loading} />
      <div className="items-grid">
        {showedItems.map((item) => (
          <ItemCard
            key={item.id}
            name={item.name}
            image={item.image}
          ></ItemCard>
        ))}
      </div>
    </>
  );
}
