import Head from "next/head";
import { useEffect, useState } from "react";
import CratesNavbar from "../../components/CratesNavbar";
import ItemCard from "../../components/ItemCard";
import SpinnerLoader from "../../components/SpinnerLoader";
import { getCrates } from "../../services/csgo";

export default function Crates() {
  const [loading, setLoading] = useState(false);
  const [crates, setCrates] = useState([]);

  useEffect(() => {
    async function getData() {
      try {
        setLoading(true);

        const { data } = await getCrates();

        setLoading(false);
        setCrates(data);
      } catch (e) {
        setCrates([]);
        console.error(e);
      }
    }
    getData();
  }, []);

  return (
    <>
      <Head>
        <title>Crates / All - CSGO DATA</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <CratesNavbar />
      <SpinnerLoader loading={loading} />
      <div className="grid w-full gap-1 py-10 mx-auto items-grid-small md:items-grid">
        {crates.map((item) => (
          <ItemCard
            key={item.id}
            name={item.name}
            image={item.image}
          ></ItemCard>
        ))}
      </div>
    </>
  );
}
