import Head from "next/head";
import { useRouter } from "next/router";
import { useEffect, useState } from "react";
import CollectiblesNavbar from "../../components/CollectiblesNavbar";
import ItemCard from "../../components/ItemCard";
import SpinnerLoader from "../../components/SpinnerLoader";
import { getCollectibles } from "../../services/csgo";

function capitalize(string) {
  if (!string) return "";
  return string.charAt(0).toUpperCase() + string.toLowerCase().slice(1);
}

export default function CollectiblesByType() {
  const router = useRouter();
  const { type } = router.query;

  const [loading, setLoading] = useState(false);
  const [collectibles, setCollectibles] = useState([]);

  useEffect(() => {
    async function getData() {
      try {
        setLoading(true);

        const { data } = await getCollectibles(type);

        setCollectibles(data);
        setLoading(false);
      } catch (e) {
        setCollectibles([]);
        console.error(e);
      }
    }
    getData();
  }, [type]);

  return (
    <>
      <Head>
        <title>
          Collectibles / {capitalize(type?.split("_").join(" "))} - CSGO DATA
        </title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <CollectiblesNavbar />
      <SpinnerLoader loading={loading} />
      <div className="items-grid">
        {collectibles.map((item) => {
          return (
            <ItemCard
              key={item.id}
              name={item.name}
              image={item.image}
              rarity={item.rarity}
            ></ItemCard>
          );
        })}
      </div>
    </>
  );
}
