import Head from "next/head";
import { useEffect, useState } from "react";
import CollectiblesNavbar from "../../components/CollectiblesNavbar";
import ItemCard from "../../components/ItemCard";
import SpinnerLoader from "../../components/SpinnerLoader";
import { getCollectibles } from "../../services/csgo";

export default function Collectibles() {
  const [loading, setLoading] = useState(false);
  const [collectibles, setCollectibles] = useState([]);

  useEffect(() => {
    async function getData() {
      try {
        setLoading(true);

        const { data } = await getCollectibles();

        setCollectibles(data);
        setLoading(false);
      } catch (e) {
        setCollectibles([]);
        console.error(e);
      }
    }
    getData();
  }, []);
  return (
    <>
      <Head>
        <title>Collectibles - CSGO ITEMS</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <CollectiblesNavbar />
      <SpinnerLoader loading={loading} />
      <div className="items-grid">
        {collectibles.map((item) => {
          return (
            <ItemCard
              key={item.id}
              name={item.name}
              image={item.image}
              rarity={item.rarity}
            ></ItemCard>
          );
        })}
      </div>
    </>
  );
}
