import Head from "next/head";
import { useRouter } from "next/router";
import { useEffect, useState } from "react";
import {
  getAgents,
  getCollectibles,
  getCollections,
  getCrates,
  getGraffiti,
  getKeys,
  getMusicKits,
  getPatches,
  getSkins,
  getStickers,
} from "../../../services/csgo";

export default function SkinById() {
  const router = useRouter();
  const { type } = router.query;
  const { id } = router.query;

  const [item, setItem] = useState({});

  useEffect(() => {
    async function getData() {
      try {
        const functionByType = {
          skins: getSkins,
          crates: getCrates,
          stickers: getStickers,
          collections: getCollections,
          collectibles: getCollectibles,
          agents: getAgents,
          graffiti: getGraffiti,
          keys: getKeys,
          patches: getPatches,
          "music-kits": getMusicKits,
        };

        const { data } = (await functionByType[type]?.()) ?? {};
        const selectedItem = data?.find((item) => item.id == id) ?? {};

        setItem(selectedItem);
      } catch (e) {
        setItem({});
        console.error(e);
      }
    }
    getData();
  }, [id, type]);

  const pageTitle = () => {
    if (item?.name) {
      return `${item?.name} - CSGO ITEMS`;
    }

    return "CSGO ITEMS";
  };

  return (
    <>
      <Head>
        <title>{pageTitle()}</title>
        <meta name="description" content="Generated by create next app" />
      </Head>
      <div className="grid gap-10 mt-10 lg:grid-cols-7">
        <div
          className={
            "flex lg:col-span-3 items-center justify-center w-full overflow-hidden bg-gray-200 rounded-md min-h-[20rem] lg:min-h-[40rem] group-hover:opacity-75 lg:h-80"
          }
        >
          <div className="px-10 lg:px-20">
            <img
              src={item?.image}
              alt={item?.name}
              loading="lazy"
              decode="async"
            />
          </div>
        </div>
        <div className="w-full lg:col-span-4">
          <div className="mb-5">
            <h1 className="text-2xl font-bold text-gray-800">{item.name}</h1>
            <p className="mt-1 text-lg text-gray-700">
              {item.rarity ?? "unknown rarity"}
            </p>
          </div>
          <div>
            <p className="mt-1 text-base text-gray-700">{item.description}</p>
          </div>
        </div>
      </div>
    </>
  );
}
