import Head from "next/head";
import { useEffect, useState } from "react";
import ItemCard from "../components/ItemCard";
import SpinnerLoader from "../components/SpinnerLoader";
import { getCollections } from "../services/csgo";

export default function Collections() {
  const [loading, setLoading] = useState(false);
  const [collections, setCollections] = useState([]);
  const [showedItems, setShowedItems] = useState([]);

  useEffect(() => {
    async function getData() {
      try {
        setLoading(true);

        const { data } = await getCollections();

        setShowedItems(data.splice(0, 20));
        setCollections(data);
        setLoading(false);
      } catch (e) {
        setCollections([]);
        console.error(e);
      }
    }
    getData();
  }, []);

  useEffect(() => {
    window.addEventListener("scroll", handleScroll);
    return () => {
      window.removeEventListener("scroll", handleScroll);
    };
  });

  const handleScroll = () => {
    const lastItemLoaded = document.querySelector(
      ".items-grid > .group:last-child"
    );
    if (lastItemLoaded) {
      const lastItemLoadedOffset =
        lastItemLoaded.offsetTop + lastItemLoaded.clientHeight;
      const pageOffset = window.pageYOffset + window.innerHeight;

      if (pageOffset > lastItemLoadedOffset) {
        if (collections.length) {
          const all = collections;
          const selected = all.splice(0, 20);
          setShowedItems([...showedItems, ...selected]);
          setCollections(all);
        }
      }
    }
  };

  return (
    <>
      <Head>
        <title>Collections - CSGO ITEMS</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <SpinnerLoader loading={loading} />
      <div className="items-grid">
        {showedItems.map((item) => {
          return (
            <ItemCard
              key={item.id}
              name={item.name}
              image={item.image}
            ></ItemCard>
          );
        })}
      </div>
    </>
  );
}
