import Head from "next/head";
import { useEffect, useState } from "react";
import ItemCard from "../components/ItemCard";
import SpinnerLoader from "../components/SpinnerLoader";
import { getCollections } from "../services/csgo";

export default function Collections() {
  const [loading, setLoading] = useState(false);
  const [collections, setCollections] = useState([]);

  useEffect(() => {
    async function getData() {
      try {
        setLoading(true);

        const { data } = await getCollections();

        setCollections(data);
        setLoading(false);
      } catch (e) {
        setCollections([]);
        console.error(e);
      }
    }
    getData();
  }, []);
  return (
    <>
      <Head>
        <title>Collections - CSGO DATA</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <SpinnerLoader loading={loading} />
      <div className="grid w-full gap-1 py-10 mx-auto items-grid-small md:items-grid">
        {collections.map((item) => {
          return (
            <ItemCard
              key={item.id}
              name={item.name}
              image={item.image}
            ></ItemCard>
          );
        })}
      </div>
    </>
  );
}
