import Head from "next/head";
import { useEffect, useState } from "react";
import ItemCard from "../components/ItemCard";
import SpinnerLoader from "../components/SpinnerLoader";
import { getCollections } from "../services/csgo";
import ItemsFilter from "../components/ItemsFilter";

export default function Collections() {
  const [loading, setLoading] = useState(false);
  const [collections, setCollections] = useState([]);
  const [showedItems, setShowedItems] = useState([]);
  const [search, setSearch] = useState("");
  const [filteredItems, setFilteredItems] = useState([]);

  useEffect(() => {
    async function getData() {
      try {
        setLoading(true);

        const { data } = await getCollections();

        setCollections([...data]);
        setShowedItems(data.splice(0, 20));
        setFilteredItems(data);
        setLoading(false);
      } catch (e) {
        setCollections([]);
        console.error(e);
      }
    }
    getData();
  }, []);

  useEffect(() => {
    window.addEventListener("scroll", handleScroll);
    return () => {
      window.removeEventListener("scroll", handleScroll);
    };
  });

  useEffect(() => {
    const filtered = collections.filter((item) => {
      if (search === "") return true;
      return item.name.toLowerCase().includes(search.toLowerCase());
    });

    setFilteredItems(filtered);
    setShowedItems(filtered.splice(0, 20));
  }, [search]);

  const handleScroll = () => {
    const lastItemLoaded = document.querySelector(
      ".items-grid > .group:last-child"
    );
    if (lastItemLoaded) {
      const lastItemLoadedOffset =
        lastItemLoaded.offsetTop + lastItemLoaded.clientHeight;
      const pageOffset = window.pageYOffset + window.innerHeight;

      if (pageOffset > lastItemLoadedOffset) {
        if (filteredItems.length) {
          const all = filteredItems;
          const selected = all.splice(0, 20);
          setShowedItems([...showedItems, ...selected]);
          setFilteredItems(all);
        }
      }
    }
  };

  return (
    <>
      <Head>
        <title>Collections - CSGO ITEMS</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <ItemsFilter filter={false} search={search} setSearch={setSearch} />
      <SpinnerLoader loading={loading} />
      <div className="items-grid">
        {showedItems.map((item) => {
          return (
            <ItemCard
              key={item.id}
              route={{ type: "collections", id: item.id }}
              name={item.name}
              image={item.image}
            ></ItemCard>
          );
        })}
      </div>
    </>
  );
}
