import Head from "next/head";
import { useEffect, useState } from "react";
import ItemCard from "../components/ItemCard";
import SpinnerLoader from "../components/SpinnerLoader";
import { getStickers } from "../services/csgo";

export default function Strikers() {
  const [loading, setLoading] = useState(false);
  const [stickers, setStickers] = useState([]);

  useEffect(() => {
    async function getData() {
      try {
        setLoading(true);

        const { data } = await getStickers();

        setStickers(data);
        setLoading(false);
      } catch (e) {
        setStickers([]);
        console.error(e);
      }
    }
    getData();
  }, []);
  return (
    <>
      <Head>
        <title>Stickers - CSGO DATA</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <SpinnerLoader loading={loading} />
      <div className="items-grid">
        {stickers.map((item) => {
          return (
            <ItemCard
              key={item.id}
              name={item.name}
              image={item.image}
              rarity={item.rarity}
            ></ItemCard>
          );
        })}
      </div>
    </>
  );
}
